change image php > phusion/baseimage

diff --git a/Dockerfile-74 b/Dockerfile-74
--- a/Dockerfile-74
+++ b/Dockerfile-74
@@ -1,29 +1,38 @@
 #
 #--------------------------------------------------------------------------
-# Image Setup
+# Image Setup.
+# 
+# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md 
+# for a list of version numbers.
 #--------------------------------------------------------------------------
 #
 
-FROM php:7.4-fpm
+FROM phusion/baseimage:bionic-1.0.0
 
 LABEL maintainer="Artem Fufaldin <artem.fufaldin@gmail.com>"
 
 # Set Environment Variables
 ENV DEBIAN_FRONTEND noninteractive
 
-#
-#--------------------------------------------------------------------------
-# Software's Installation
-#--------------------------------------------------------------------------
-#
-#
+# Install Laravel requirements
+RUN set -xe; \
+    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main" | tee -a /etc/apt/sources.list && \
+    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E5267A6C && \
+    apt-get update && \
+    apt-get -o DPkg::options::="--force-confold" -y upgrade && \
+    apt-get -o DPkg::options::="--force-confold" -y install \
+        php7.4-fpm \
+        php7.4-bcmath \
+        php7.4-xml \
+        php7.4-mbstring
 
-RUN set -eux \
-    apt-get update \
-    apt-get upgrade -y \
-    apt-get install -y --no-install-recommends \
-            apt-utils \
-    pecl channel-update pecl.php.net && \
-    # Install the PHP bcmath library
-    docker-php-ext-install bcmath && \
-    rm -rf /var/lib/apt/lists/*
+# Composer
+COPY ./install_composer.sh /root/install_composer.sh
+RUN . /root/install_composer.sh && \
+   rm /root/install_composer.sh
+
+# Use baseimage-docker's init system.
+CMD ["/sbin/my_init"]
+
+# Clean up
+RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
